language: python
python:
- 2.7
- 3.5
- 3.6
- 3.7
install:
- pip install nose
- pip install flake8
- pip install coveralls
script:
- flake8 esrijson tests
- coverage run --source=esrijson setup.py test
- coverage report -m
